#!/usr/bin/env python3
"""Generate all publication-quality figures for the RLVR-Maths research report.

Reads raw metrics.jsonl from each v3b run and produces 10 figures as both
PNG (600 dpi) and PDF, using serif fonts and the Wong colorblind-safe palette.

Also saves per-figure reproduction scripts to reports/figures/.

Usage:
    uv run python scripts/gen_research_figures.py
"""

import inspect
import json
import textwrap
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# ---------------------------------------------------------------------------
# Style config — figure-forge spec
# ---------------------------------------------------------------------------
plt.rcParams.update({
    "font.family": "serif",
    "font.size": 10,
    "axes.titlesize": 12,
    "axes.labelsize": 11,
    "legend.fontsize": 9,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "figure.dpi": 150,
    "savefig.dpi": 600,
    "savefig.bbox": "tight",
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
    "axes.spines.top": False,
    "axes.spines.right": False,
})

# Wong colorblind-safe palette
CB_GREEN = "#009E73"
CB_RED = "#D55E00"
CB_BLUE = "#0072B2"
CB_ORANGE = "#E69F00"
CB_PURPLE = "#CC79A7"
CB_SKY = "#56B4E9"

MODEL_COLORS = {
    "GPT-OSS-20B": CB_BLUE,
    "Qwen3-30B-Instruct": CB_GREEN,
    "Qwen3-30B-Think": CB_RED,
}
MODEL_MARKERS = {
    "GPT-OSS-20B": "o",
    "Qwen3-30B-Instruct": "s",
    "Qwen3-30B-Think": "^",
}

OUTDIR = Path(__file__).resolve().parent.parent / "reports" / "figures"
DATA_ROOT = Path("/tmp/tinker-examples/rlvr")

RUNS = {
    "GPT-OSS-20B": DATA_ROOT / "gptoss-20b-v3b" / "metrics.jsonl",
    "Qwen3-30B-Instruct": DATA_ROOT / "qwen3-30b-instruct-v3b" / "metrics.jsonl",
    "Qwen3-30B-Think": DATA_ROOT / "qwen3-30b-think-v3b" / "metrics.jsonl",
}


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------
def load_metrics(path: Path) -> list[dict]:
    with open(path) as f:
        return [json.loads(line) for line in f]


def split_train_eval(data: list[dict]):
    """Split into train rows (have env/all/correct) and eval rows (have test/test/...)."""
    train = [d for d in data if "env/all/correct" in d]
    evl = [d for d in data if "test/test/env/all/correct" in d]
    return train, evl


def load_all():
    """Return dict[model_name] -> (train_rows, eval_rows)."""
    result = {}
    for name, path in RUNS.items():
        data = load_metrics(path)
        result[name] = split_train_eval(data)
    return result


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def save(fig, name: str, func=None):
    """Save figure as PNG + PDF, and optionally save the source function as a script."""
    png_path = OUTDIR / f"{name}.png"
    pdf_path = OUTDIR / f"{name}.pdf"
    fig.savefig(png_path, dpi=600, bbox_inches="tight")
    fig.savefig(pdf_path, bbox_inches="tight")
    plt.close(fig)
    print(f"  saved {png_path}")
    print(f"  saved {pdf_path}")

    # Save per-figure reproduction script
    if func is not None:
        script_path = OUTDIR / f"{name}.py"
        source = inspect.getsource(func)
        script_content = textwrap.dedent(f'''\
#!/usr/bin/env python3
"""Reproduction script for {name}. Generated by gen_research_figures.py."""
import json, sys
from pathlib import Path
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# Style
plt.rcParams.update({{
    "font.family": "serif", "font.size": 10, "axes.titlesize": 12,
    "axes.labelsize": 11, "legend.fontsize": 9, "xtick.labelsize": 9,
    "ytick.labelsize": 9, "savefig.dpi": 600, "savefig.bbox": "tight",
    "pdf.fonttype": 42, "ps.fonttype": 42,
    "axes.spines.top": False, "axes.spines.right": False,
}})

CB_GREEN = "#009E73"; CB_RED = "#D55E00"; CB_BLUE = "#0072B2"
CB_ORANGE = "#E69F00"; CB_PURPLE = "#CC79A7"; CB_SKY = "#56B4E9"
MODEL_COLORS = {{"GPT-OSS-20B": CB_BLUE, "Qwen3-30B-Instruct": CB_GREEN, "Qwen3-30B-Think": CB_RED}}
MODEL_MARKERS = {{"GPT-OSS-20B": "o", "Qwen3-30B-Instruct": "s", "Qwen3-30B-Think": "^"}}

DATA_ROOT = Path("/tmp/tinker-examples/rlvr")
RUNS = {{
    "GPT-OSS-20B": DATA_ROOT / "gptoss-20b-v3b" / "metrics.jsonl",
    "Qwen3-30B-Instruct": DATA_ROOT / "qwen3-30b-instruct-v3b" / "metrics.jsonl",
    "Qwen3-30B-Think": DATA_ROOT / "qwen3-30b-think-v3b" / "metrics.jsonl",
}}

def load_all():
    result = {{}}
    for name, path in RUNS.items():
        data = [json.loads(l) for l in open(path)]
        train = [d for d in data if "env/all/correct" in d]
        evl = [d for d in data if "test/test/env/all/correct" in d]
        result[name] = (train, evl)
    return result

def save(fig, name):
    fig.savefig(f"{{name}}.png", dpi=600, bbox_inches="tight")
    fig.savefig(f"{{name}}.pdf", bbox_inches="tight")
    print(f"Saved {{name}}.png and {{name}}.pdf")

# --- Figure function ---
''')
        # Dedent the source and append it
        script_content += source + f"\n\nif __name__ == '__main__':\n    all_data = load_all()\n    {func.__name__}(all_data)\n"
        script_path.write_text(script_content)


# ---------------------------------------------------------------------------
# Figure 1: Eval trajectory comparison (correct over steps)
# ---------------------------------------------------------------------------
def fig1_eval_trajectory(all_data):
    fig, ax = plt.subplots(figsize=(8, 5))
    for name, (train, evl) in all_data.items():
        steps = [d["step"] for d in evl]
        correct = [d["test/test/env/all/correct"] for d in evl]
        ax.plot(steps, correct, color=MODEL_COLORS[name], marker=MODEL_MARKERS[name],
                linewidth=2, markersize=7, label=name)
        # Annotate peak
        peak_idx = int(np.argmax(correct))
        ax.annotate(f"peak {correct[peak_idx]:.1%}",
                     xy=(steps[peak_idx], correct[peak_idx]),
                     xytext=(0, 12), textcoords="offset points",
                     fontsize=8, ha="center", color=MODEL_COLORS[name],
                     arrowprops=dict(arrowstyle="-", color=MODEL_COLORS[name], lw=0.8))
    ax.set_xlabel("Training step")
    ax.set_ylabel("Eval accuracy (fraction correct)")
    ax.set_title("Eval Accuracy Over Training")
    ax.legend()
    ax.set_ylim(0, 0.75)
    ax.grid(axis="y", alpha=0.3)
    save(fig, "01_eval_trajectory", fig1_eval_trajectory)


# ---------------------------------------------------------------------------
# Figure 2: P(correct|boxed) decomposition over eval points
# ---------------------------------------------------------------------------
def fig2_pcorrect_given_boxed(all_data):
    fig, axes = plt.subplots(1, 3, figsize=(14, 4.5), sharey=True)
    for ax, (name, (train, evl)) in zip(axes, all_data.items()):
        steps = [d["step"] for d in evl]
        correct = np.array([d["test/test/env/all/correct"] for d in evl])
        boxed = np.array([d["test/test/env/all/format_boxed"] for d in evl])
        p_corr_given_boxed = np.where(boxed > 0, correct / boxed, 0)

        ax.plot(steps, boxed, color=CB_SKY, marker="s", linewidth=2, label="P(boxed)")
        ax.plot(steps, correct, color=MODEL_COLORS[name], marker="o", linewidth=2, label="P(correct)")
        ax.plot(steps, p_corr_given_boxed, color=CB_ORANGE, marker="^", linewidth=2,
                linestyle="--", label="P(correct|boxed)")
        ax.set_xlabel("Training step")
        ax.set_title(name)
        ax.legend(fontsize=8)
        ax.set_ylim(0, 1.05)
        ax.grid(axis="y", alpha=0.3)
    axes[0].set_ylabel("Probability")
    fig.suptitle("Eval: Decomposing Correctness via Format Compliance", fontsize=12, y=1.02)
    fig.tight_layout()
    save(fig, "02_pcorrect_decomposition", fig2_pcorrect_given_boxed)


# ---------------------------------------------------------------------------
# Figure 3: Token compression trajectory (ac_tokens_per_turn over train steps)
# ---------------------------------------------------------------------------
def fig3_token_compression(all_data):
    fig, ax = plt.subplots(figsize=(8, 5))
    for name, (train, evl) in all_data.items():
        steps = [d["step"] for d in train]
        tokens = [d["env/all/ac_tokens_per_turn"] for d in train]
        ax.plot(steps, tokens, color=MODEL_COLORS[name], linewidth=1.5, alpha=0.7, label=name)
    ax.set_xlabel("Training step")
    ax.set_ylabel("Mean tokens per turn (train)")
    ax.set_title("Response Length Compression During Training")
    ax.legend()
    ax.grid(axis="y", alpha=0.3)
    save(fig, "03_token_compression", fig3_token_compression)


# ---------------------------------------------------------------------------
# Figure 4: GPT-OSS analysis channel — token length over steps
# ---------------------------------------------------------------------------
def fig4_gptoss_channel_evolution(all_data):
    train, evl = all_data["GPT-OSS-20B"]
    fig, ax = plt.subplots(figsize=(8, 5))

    train_steps = [d["step"] for d in train]
    train_tokens = [d["env/all/ac_tokens_per_turn"] for d in train]
    eval_steps = [d["step"] for d in evl]
    eval_tokens = [d["test/test/env/all/ac_tokens_per_turn"] for d in evl]

    ax.plot(train_steps, train_tokens, color=CB_BLUE, linewidth=1.5, alpha=0.7, label="Train")
    ax.plot(eval_steps, eval_tokens, color=CB_ORANGE, marker="D", linewidth=2,
            markersize=7, label="Eval")

    if len(train_tokens) > 1:
        ratio = train_tokens[-1] / train_tokens[0]
        ax.annotate(f"compression {ratio:.2f}x",
                     xy=(train_steps[-1], train_tokens[-1]),
                     xytext=(-60, 20), textcoords="offset points",
                     fontsize=8, color=CB_BLUE,
                     arrowprops=dict(arrowstyle="->", color=CB_BLUE, lw=0.8))

    ax.set_xlabel("Training step")
    ax.set_ylabel("Mean tokens per turn")
    ax.set_title("GPT-OSS-20B: Response Length (Train vs Eval)")
    ax.legend()
    ax.grid(axis="y", alpha=0.3)
    save(fig, "04_gptoss_channel_evolution", fig4_gptoss_channel_evolution)


# ---------------------------------------------------------------------------
# Figure 5: Entropy comparison bar chart (initial vs final for each model)
# ---------------------------------------------------------------------------
def fig5_entropy_comparison(all_data):
    fig, ax = plt.subplots(figsize=(7, 5))
    models = list(all_data.keys())
    x = np.arange(len(models))
    width = 0.35

    initial_entropy = []
    final_entropy = []
    for name in models:
        train, _ = all_data[name]
        entropies = [d["optim/entropy"] for d in train if "optim/entropy" in d]
        initial_entropy.append(entropies[0])
        final_entropy.append(entropies[-1])

    bars1 = ax.bar(x - width / 2, initial_entropy, width, label="Initial", color=CB_SKY, edgecolor="white")
    bars2 = ax.bar(x + width / 2, final_entropy, width, label="Final", color=CB_BLUE, edgecolor="white")

    for bar in bars1:
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.01,
                f"{bar.get_height():.3f}", ha="center", va="bottom", fontsize=8)
    for bar in bars2:
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.01,
                f"{bar.get_height():.3f}", ha="center", va="bottom", fontsize=8)

    ax.set_xticks(x)
    ax.set_xticklabels(models, fontsize=9)
    ax.set_ylabel("Entropy")
    ax.set_title("Policy Entropy: Start vs End of Training")
    ax.legend()
    ax.grid(axis="y", alpha=0.3)
    save(fig, "05_entropy_comparison", fig5_entropy_comparison)


# ---------------------------------------------------------------------------
# Figure 6: Reward decomposition stacked bar
# ---------------------------------------------------------------------------
def fig6_reward_decomposition(all_data):
    """Three-way reward decomposition at final train step.

    reward = correct + 0.15*(boxed-1) + 0.15*(eos-1)
    """
    fig, ax = plt.subplots(figsize=(8, 5))
    models = list(all_data.keys())
    x = np.arange(len(models))
    width = 0.6
    FORMAT_COEF = 0.15  # v3b hyperparameter
    EOS_COEF = 0.15

    correct_vals, boxed_pen, eos_pen, reward_vals = [], [], [], []
    for name in models:
        train, _ = all_data[name]
        last = train[-1]
        c = last["env/all/correct"]
        b = last["env/all/format_boxed"]
        e = last["env/all/format_eos"]
        r = last["env/all/reward/total"]
        correct_vals.append(c)
        boxed_pen.append(FORMAT_COEF * (1 - b))
        eos_pen.append(EOS_COEF * (1 - e))
        reward_vals.append(r)

    correct_arr = np.array(correct_vals)
    boxed_arr = np.array(boxed_pen)
    eos_arr = np.array(eos_pen)
    reward_arr = np.array(reward_vals)

    ax.bar(x, reward_arr, width, label="Net reward", color=CB_GREEN, edgecolor="white")
    ax.bar(x, boxed_arr, width, bottom=reward_arr,
           label=f"Box penalty (coef={FORMAT_COEF})", color=CB_ORANGE, alpha=0.8, edgecolor="white")
    ax.bar(x, eos_arr, width, bottom=reward_arr + boxed_arr,
           label=f"EOS penalty (coef={EOS_COEF})", color=CB_RED, alpha=0.7, edgecolor="white")

    for i in range(len(models)):
        ax.text(i, correct_arr[i] + 0.01, f"correct={correct_arr[i]:.1%}", ha="center", fontsize=8)
        ax.text(i, reward_arr[i] / 2, f"r={reward_arr[i]:.3f}", ha="center", fontsize=8,
                color="white", fontweight="bold")

    ax.set_xticks(x)
    ax.set_xticklabels(models, fontsize=9)
    ax.set_ylabel("Value")
    ax.set_title("Final Train Step: Reward = correct + penalties")
    ax.legend(fontsize=8)
    ax.grid(axis="y", alpha=0.3)
    save(fig, "06_reward_decomposition", fig6_reward_decomposition)


# ---------------------------------------------------------------------------
# Figure 7: Think vs Instruct token budget
# ---------------------------------------------------------------------------
def fig7_think_token_trajectory(all_data):
    """Think model token budget across training — shows bimodality via train vs eval split."""
    fig, ax = plt.subplots(figsize=(8, 5))

    train_think, eval_think = all_data["Qwen3-30B-Think"]
    train_instruct, eval_instruct = all_data["Qwen3-30B-Instruct"]

    steps_t = [d["step"] for d in train_think]
    tokens_t = [d["env/all/ac_tokens_per_turn"] for d in train_think]
    ax.plot(steps_t, tokens_t, color=CB_RED, linewidth=1.5, alpha=0.7, label="Think (train)")

    eval_steps_t = [d["step"] for d in eval_think]
    eval_tokens_t = [d["test/test/env/all/ac_tokens_per_turn"] for d in eval_think]
    ax.plot(eval_steps_t, eval_tokens_t, color=CB_RED, marker="^", linewidth=2,
            markersize=8, linestyle="--", label="Think (eval)")

    steps_i = [d["step"] for d in train_instruct]
    tokens_i = [d["env/all/ac_tokens_per_turn"] for d in train_instruct]
    ax.plot(steps_i, tokens_i, color=CB_GREEN, linewidth=1.5, alpha=0.5, label="Instruct (train)")

    eval_steps_i = [d["step"] for d in eval_instruct]
    eval_tokens_i = [d["test/test/env/all/ac_tokens_per_turn"] for d in eval_instruct]
    ax.plot(eval_steps_i, eval_tokens_i, color=CB_GREEN, marker="s", linewidth=2,
            markersize=7, linestyle="--", alpha=0.7, label="Instruct (eval)")

    ax.set_xlabel("Training step")
    ax.set_ylabel("Mean tokens per turn")
    ax.set_title("Think vs Instruct: Token Budget Over Training")
    ax.legend()
    ax.grid(axis="y", alpha=0.3)
    save(fig, "07_think_token_budget", fig7_think_token_trajectory)


# ---------------------------------------------------------------------------
# Figure 8: Truncation rate trajectory
# ---------------------------------------------------------------------------
def fig8_truncation_rate(all_data):
    fig, ax = plt.subplots(figsize=(8, 5))
    for name, (train, evl) in all_data.items():
        color = MODEL_COLORS[name]
        steps = [d["step"] for d in train]
        trunc = [1 - d["env/all/format_eos"] for d in train]
        ax.plot(steps, trunc, color=color, linewidth=1.2, alpha=0.6, label=f"{name} (train)")

        eval_steps = [d["step"] for d in evl]
        eval_trunc = [1 - d["test/test/env/all/format_eos"] for d in evl]
        ax.plot(eval_steps, eval_trunc, color=color, marker=MODEL_MARKERS[name],
                linewidth=2, markersize=7, linestyle="--", label=f"{name} (eval)")

    ax.set_xlabel("Training step")
    ax.set_ylabel("Truncation rate (1 \u2212 format_eos)")
    ax.set_title("Truncation Rate Over Training")
    ax.legend(fontsize=8)
    ax.set_ylim(bottom=0)
    ax.grid(axis="y", alpha=0.3)
    save(fig, "08_truncation_rate", fig8_truncation_rate)


# ---------------------------------------------------------------------------
# Figure 9: Grader false negative rate by model
# ---------------------------------------------------------------------------
def fig9_grader_accuracy(all_data):
    """Per-model grader false negative rates from experiment-log-session2.md.

    Actual measured FN rates on wrong-but-boxed answers:
    - GPT-OSS v3b: 14% (1/7)
    - Instruct v3b: 24% (5/21)
    - Think v3b: had a separate bug (\\boxed{answer} literal accepted)
    """
    fig, ax = plt.subplots(figsize=(7, 5))

    models = ["GPT-OSS-20B", "Qwen3-30B-Instruct", "Qwen3-30B-Think"]
    fn_counts = [1, 5]
    sample_sizes = [7, 21, None]
    fn_rates = [fn_counts[0] / sample_sizes[0], fn_counts[1] / sample_sizes[1], np.nan]
    colors = [MODEL_COLORS[m] for m in models]

    x = np.arange(len(models))
    bars = ax.bar(x[:2], fn_rates[:2], width=0.5, color=colors[:2], edgecolor="white")

    for i, bar in enumerate(bars):
        n = sample_sizes[i]
        c = fn_counts[i]
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.01,
                f"{c/n:.0%} ({c}/{n})", ha="center", fontsize=10, fontweight="bold")

    ax.bar(x[2], 0.02, width=0.5, color=colors[2], edgecolor="white", alpha=0.4)
    ax.text(x[2], 0.05, "grader bug:\n\\boxed{{answer}}\nliteral accepted",
            ha="center", fontsize=8, fontstyle="italic", color=CB_RED)

    ax.set_xticks(x)
    ax.set_xticklabels(models, fontsize=9)
    ax.set_ylabel("False negative rate (wrong answers graded correct)")
    ax.set_title("LLM Grader False Negative Rate by Model")
    ax.set_ylim(0, 0.35)
    ax.grid(axis="y", alpha=0.3)

    ax.text(0.98, 0.62,
            "Common FN causes:\n"
            "  LaTeX \\text{{}} wrapping\n"
            "  Variable name diffs\n"
            "  Double-boxing\n\n"
            "Small n (7, 21) \u2014\n"
            "rates are indicative",
            transform=ax.transAxes, ha="right", va="top", fontsize=8,
            color="gray", family="monospace",
            bbox=dict(boxstyle="round,pad=0.3", facecolor="whitesmoke", edgecolor="lightgray"))
    save(fig, "09_grader_accuracy", fig9_grader_accuracy)


# ---------------------------------------------------------------------------
# Figure 10: Train vs eval gap over time per model
# ---------------------------------------------------------------------------
def fig10_train_eval_gap(all_data):
    fig, ax = plt.subplots(figsize=(8, 5))
    for name, (train, evl) in all_data.items():
        color = MODEL_COLORS[name]
        eval_steps = [d["step"] for d in evl]
        eval_correct = {d["step"]: d["test/test/env/all/correct"] for d in evl}
        train_correct = {d["step"]: d["env/all/correct"] for d in train}

        gaps = []
        steps_plot = []
        for step in eval_steps:
            if step in train_correct:
                gap = eval_correct[step] - train_correct[step]
                gaps.append(gap)
                steps_plot.append(step)

        if steps_plot:
            ax.plot(steps_plot, gaps, color=color, marker=MODEL_MARKERS[name],
                    linewidth=2, markersize=7, label=name)

    ax.axhline(0, color="gray", linewidth=0.8, linestyle=":")
    ax.set_xlabel("Training step")
    ax.set_ylabel("Eval \u2212 Train accuracy gap")
    ax.set_title("Generalization Gap Over Training")
    ax.legend()
    ax.grid(axis="y", alpha=0.3)

    ax.text(0.98, 0.95, "positive gap expected (eval uses lower temp)",
            transform=ax.transAxes, ha="right", va="top", fontsize=8, color="gray")
    ax.text(0.98, 0.05, "negative gap = eval-specific failure",
            transform=ax.transAxes, ha="right", va="bottom", fontsize=8, color="gray")
    save(fig, "10_train_eval_gap", fig10_train_eval_gap)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    OUTDIR.mkdir(parents=True, exist_ok=True)
    print(f"Output directory: {OUTDIR}")

    all_data = load_all()
    print(f"Loaded {len(all_data)} runs\n")

    print("Generating figures...")
    fig1_eval_trajectory(all_data)
    fig2_pcorrect_given_boxed(all_data)
    fig3_token_compression(all_data)
    fig4_gptoss_channel_evolution(all_data)
    fig5_entropy_comparison(all_data)
    fig6_reward_decomposition(all_data)
    fig7_think_token_trajectory(all_data)
    fig8_truncation_rate(all_data)
    fig9_grader_accuracy(all_data)
    fig10_train_eval_gap(all_data)

    n_png = len(list(OUTDIR.glob("*.png")))
    n_pdf = len(list(OUTDIR.glob("*.pdf")))
    n_py = len(list(OUTDIR.glob("*.py")))
    print(f"\nDone. {n_png} PNGs + {n_pdf} PDFs + {n_py} scripts in {OUTDIR}")


if __name__ == "__main__":
    main()
