#!/usr/bin/env python3
"""Reproduction script for 02_pcorrect_decomposition. Generated by gen_research_figures.py."""
import json, sys
from pathlib import Path
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# Style
plt.rcParams.update({
    "font.family": "serif", "font.size": 10, "axes.titlesize": 12,
    "axes.labelsize": 11, "legend.fontsize": 9, "xtick.labelsize": 9,
    "ytick.labelsize": 9, "savefig.dpi": 600, "savefig.bbox": "tight",
    "pdf.fonttype": 42, "ps.fonttype": 42,
    "axes.spines.top": False, "axes.spines.right": False,
})

CB_GREEN = "#009E73"; CB_RED = "#D55E00"; CB_BLUE = "#0072B2"
CB_ORANGE = "#E69F00"; CB_PURPLE = "#CC79A7"; CB_SKY = "#56B4E9"
MODEL_COLORS = {"GPT-OSS-20B": CB_BLUE, "Qwen3-30B-Instruct": CB_GREEN, "Qwen3-30B-Think": CB_RED}
MODEL_MARKERS = {"GPT-OSS-20B": "o", "Qwen3-30B-Instruct": "s", "Qwen3-30B-Think": "^"}

DATA_ROOT = Path("/tmp/tinker-examples/rlvr")
RUNS = {
    "GPT-OSS-20B": DATA_ROOT / "gptoss-20b-v3b" / "metrics.jsonl",
    "Qwen3-30B-Instruct": DATA_ROOT / "qwen3-30b-instruct-v3b" / "metrics.jsonl",
    "Qwen3-30B-Think": DATA_ROOT / "qwen3-30b-think-v3b" / "metrics.jsonl",
}

def load_all():
    result = {}
    for name, path in RUNS.items():
        data = [json.loads(l) for l in open(path)]
        train = [d for d in data if "env/all/correct" in d]
        evl = [d for d in data if "test/test/env/all/correct" in d]
        result[name] = (train, evl)
    return result

def save(fig, name):
    fig.savefig(f"{name}.png", dpi=600, bbox_inches="tight")
    fig.savefig(f"{name}.pdf", bbox_inches="tight")
    print(f"Saved {name}.png and {name}.pdf")

# --- Figure function ---
def fig2_pcorrect_given_boxed(all_data):
    fig, axes = plt.subplots(1, 3, figsize=(14, 4.5), sharey=True)
    for ax, (name, (train, evl)) in zip(axes, all_data.items()):
        steps = [d["step"] for d in evl]
        correct = np.array([d["test/test/env/all/correct"] for d in evl])
        boxed = np.array([d["test/test/env/all/format_boxed"] for d in evl])
        p_corr_given_boxed = np.where(boxed > 0, correct / boxed, 0)

        ax.plot(steps, boxed, color=CB_SKY, marker="s", linewidth=2, label="P(boxed)")
        ax.plot(steps, correct, color=MODEL_COLORS[name], marker="o", linewidth=2, label="P(correct)")
        ax.plot(steps, p_corr_given_boxed, color=CB_ORANGE, marker="^", linewidth=2,
                linestyle="--", label="P(correct|boxed)")
        ax.set_xlabel("Training step")
        ax.set_title(name)
        ax.legend(fontsize=8)
        ax.set_ylim(0, 1.05)
        ax.grid(axis="y", alpha=0.3)
    axes[0].set_ylabel("Probability")
    fig.suptitle("Eval: Decomposing Correctness via Format Compliance", fontsize=12, y=1.02)
    fig.tight_layout()
    save(fig, "02_pcorrect_decomposition", fig2_pcorrect_given_boxed)


if __name__ == '__main__':
    all_data = load_all()
    fig2_pcorrect_given_boxed(all_data)
