#!/usr/bin/env python3
"""Reproduction script for 04_gptoss_channel_evolution. Generated by gen_research_figures.py."""
import json, sys
from pathlib import Path
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# Style
plt.rcParams.update({
    "font.family": "serif", "font.size": 10, "axes.titlesize": 12,
    "axes.labelsize": 11, "legend.fontsize": 9, "xtick.labelsize": 9,
    "ytick.labelsize": 9, "savefig.dpi": 600, "savefig.bbox": "tight",
    "pdf.fonttype": 42, "ps.fonttype": 42,
    "axes.spines.top": False, "axes.spines.right": False,
})

CB_GREEN = "#009E73"; CB_RED = "#D55E00"; CB_BLUE = "#0072B2"
CB_ORANGE = "#E69F00"; CB_PURPLE = "#CC79A7"; CB_SKY = "#56B4E9"
MODEL_COLORS = {"GPT-OSS-20B": CB_BLUE, "Qwen3-30B-Instruct": CB_GREEN, "Qwen3-30B-Think": CB_RED}
MODEL_MARKERS = {"GPT-OSS-20B": "o", "Qwen3-30B-Instruct": "s", "Qwen3-30B-Think": "^"}

DATA_ROOT = Path("/tmp/tinker-examples/rlvr")
RUNS = {
    "GPT-OSS-20B": DATA_ROOT / "gptoss-20b-v3b" / "metrics.jsonl",
    "Qwen3-30B-Instruct": DATA_ROOT / "qwen3-30b-instruct-v3b" / "metrics.jsonl",
    "Qwen3-30B-Think": DATA_ROOT / "qwen3-30b-think-v3b" / "metrics.jsonl",
}

def load_all():
    result = {}
    for name, path in RUNS.items():
        data = [json.loads(l) for l in open(path)]
        train = [d for d in data if "env/all/correct" in d]
        evl = [d for d in data if "test/test/env/all/correct" in d]
        result[name] = (train, evl)
    return result

def save(fig, name):
    fig.savefig(f"{name}.png", dpi=600, bbox_inches="tight")
    fig.savefig(f"{name}.pdf", bbox_inches="tight")
    print(f"Saved {name}.png and {name}.pdf")

# --- Figure function ---
def fig4_gptoss_channel_evolution(all_data):
    train, evl = all_data["GPT-OSS-20B"]
    fig, ax = plt.subplots(figsize=(8, 5))

    train_steps = [d["step"] for d in train]
    train_tokens = [d["env/all/ac_tokens_per_turn"] for d in train]
    eval_steps = [d["step"] for d in evl]
    eval_tokens = [d["test/test/env/all/ac_tokens_per_turn"] for d in evl]

    ax.plot(train_steps, train_tokens, color=CB_BLUE, linewidth=1.5, alpha=0.7, label="Train")
    ax.plot(eval_steps, eval_tokens, color=CB_ORANGE, marker="D", linewidth=2,
            markersize=7, label="Eval")

    if len(train_tokens) > 1:
        ratio = train_tokens[-1] / train_tokens[0]
        ax.annotate(f"compression {ratio:.2f}x",
                     xy=(train_steps[-1], train_tokens[-1]),
                     xytext=(-60, 20), textcoords="offset points",
                     fontsize=8, color=CB_BLUE,
                     arrowprops=dict(arrowstyle="->", color=CB_BLUE, lw=0.8))

    ax.set_xlabel("Training step")
    ax.set_ylabel("Mean tokens per turn")
    ax.set_title("GPT-OSS-20B: Response Length (Train vs Eval)")
    ax.legend()
    ax.grid(axis="y", alpha=0.3)
    save(fig, "04_gptoss_channel_evolution", fig4_gptoss_channel_evolution)


if __name__ == '__main__':
    all_data = load_all()
    fig4_gptoss_channel_evolution(all_data)
