#!/usr/bin/env python3
"""Reproduction script for 05_entropy_comparison. Generated by gen_research_figures.py."""
import json, sys
from pathlib import Path
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# Style
plt.rcParams.update({
    "font.family": "serif", "font.size": 10, "axes.titlesize": 12,
    "axes.labelsize": 11, "legend.fontsize": 9, "xtick.labelsize": 9,
    "ytick.labelsize": 9, "savefig.dpi": 600, "savefig.bbox": "tight",
    "pdf.fonttype": 42, "ps.fonttype": 42,
    "axes.spines.top": False, "axes.spines.right": False,
})

CB_GREEN = "#009E73"; CB_RED = "#D55E00"; CB_BLUE = "#0072B2"
CB_ORANGE = "#E69F00"; CB_PURPLE = "#CC79A7"; CB_SKY = "#56B4E9"
MODEL_COLORS = {"GPT-OSS-20B": CB_BLUE, "Qwen3-30B-Instruct": CB_GREEN, "Qwen3-30B-Think": CB_RED}
MODEL_MARKERS = {"GPT-OSS-20B": "o", "Qwen3-30B-Instruct": "s", "Qwen3-30B-Think": "^"}

DATA_ROOT = Path("/tmp/tinker-examples/rlvr")
RUNS = {
    "GPT-OSS-20B": DATA_ROOT / "gptoss-20b-v3b" / "metrics.jsonl",
    "Qwen3-30B-Instruct": DATA_ROOT / "qwen3-30b-instruct-v3b" / "metrics.jsonl",
    "Qwen3-30B-Think": DATA_ROOT / "qwen3-30b-think-v3b" / "metrics.jsonl",
}

def load_all():
    result = {}
    for name, path in RUNS.items():
        data = [json.loads(l) for l in open(path)]
        train = [d for d in data if "env/all/correct" in d]
        evl = [d for d in data if "test/test/env/all/correct" in d]
        result[name] = (train, evl)
    return result

def save(fig, name):
    fig.savefig(f"{name}.png", dpi=600, bbox_inches="tight")
    fig.savefig(f"{name}.pdf", bbox_inches="tight")
    print(f"Saved {name}.png and {name}.pdf")

# --- Figure function ---
def fig5_entropy_comparison(all_data):
    fig, ax = plt.subplots(figsize=(7, 5))
    models = list(all_data.keys())
    x = np.arange(len(models))
    width = 0.35

    initial_entropy = []
    final_entropy = []
    for name in models:
        train, _ = all_data[name]
        entropies = [d["optim/entropy"] for d in train if "optim/entropy" in d]
        initial_entropy.append(entropies[0])
        final_entropy.append(entropies[-1])

    bars1 = ax.bar(x - width / 2, initial_entropy, width, label="Initial", color=CB_SKY, edgecolor="white")
    bars2 = ax.bar(x + width / 2, final_entropy, width, label="Final", color=CB_BLUE, edgecolor="white")

    for bar in bars1:
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.01,
                f"{bar.get_height():.3f}", ha="center", va="bottom", fontsize=8)
    for bar in bars2:
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.01,
                f"{bar.get_height():.3f}", ha="center", va="bottom", fontsize=8)

    ax.set_xticks(x)
    ax.set_xticklabels(models, fontsize=9)
    ax.set_ylabel("Entropy")
    ax.set_title("Policy Entropy: Start vs End of Training")
    ax.legend()
    ax.grid(axis="y", alpha=0.3)
    save(fig, "05_entropy_comparison", fig5_entropy_comparison)


if __name__ == '__main__':
    all_data = load_all()
    fig5_entropy_comparison(all_data)
