#!/usr/bin/env python3
"""Reproduction script for 06_reward_decomposition. Generated by gen_research_figures.py."""
import json, sys
from pathlib import Path
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# Style
plt.rcParams.update({
    "font.family": "serif", "font.size": 10, "axes.titlesize": 12,
    "axes.labelsize": 11, "legend.fontsize": 9, "xtick.labelsize": 9,
    "ytick.labelsize": 9, "savefig.dpi": 600, "savefig.bbox": "tight",
    "pdf.fonttype": 42, "ps.fonttype": 42,
    "axes.spines.top": False, "axes.spines.right": False,
})

CB_GREEN = "#009E73"; CB_RED = "#D55E00"; CB_BLUE = "#0072B2"
CB_ORANGE = "#E69F00"; CB_PURPLE = "#CC79A7"; CB_SKY = "#56B4E9"
MODEL_COLORS = {"GPT-OSS-20B": CB_BLUE, "Qwen3-30B-Instruct": CB_GREEN, "Qwen3-30B-Think": CB_RED}
MODEL_MARKERS = {"GPT-OSS-20B": "o", "Qwen3-30B-Instruct": "s", "Qwen3-30B-Think": "^"}

DATA_ROOT = Path("/tmp/tinker-examples/rlvr")
RUNS = {
    "GPT-OSS-20B": DATA_ROOT / "gptoss-20b-v3b" / "metrics.jsonl",
    "Qwen3-30B-Instruct": DATA_ROOT / "qwen3-30b-instruct-v3b" / "metrics.jsonl",
    "Qwen3-30B-Think": DATA_ROOT / "qwen3-30b-think-v3b" / "metrics.jsonl",
}

def load_all():
    result = {}
    for name, path in RUNS.items():
        data = [json.loads(l) for l in open(path)]
        train = [d for d in data if "env/all/correct" in d]
        evl = [d for d in data if "test/test/env/all/correct" in d]
        result[name] = (train, evl)
    return result

def save(fig, name):
    fig.savefig(f"{name}.png", dpi=600, bbox_inches="tight")
    fig.savefig(f"{name}.pdf", bbox_inches="tight")
    print(f"Saved {name}.png and {name}.pdf")

# --- Figure function ---
def fig6_reward_decomposition(all_data):
    """Three-way reward decomposition at final train step.

    reward = correct + 0.15*(boxed-1) + 0.15*(eos-1)
    """
    fig, ax = plt.subplots(figsize=(8, 5))
    models = list(all_data.keys())
    x = np.arange(len(models))
    width = 0.6
    FORMAT_COEF = 0.15  # v3b hyperparameter
    EOS_COEF = 0.15

    correct_vals, boxed_pen, eos_pen, reward_vals = [], [], [], []
    for name in models:
        train, _ = all_data[name]
        last = train[-1]
        c = last["env/all/correct"]
        b = last["env/all/format_boxed"]
        e = last["env/all/format_eos"]
        r = last["env/all/reward/total"]
        correct_vals.append(c)
        boxed_pen.append(FORMAT_COEF * (1 - b))
        eos_pen.append(EOS_COEF * (1 - e))
        reward_vals.append(r)

    correct_arr = np.array(correct_vals)
    boxed_arr = np.array(boxed_pen)
    eos_arr = np.array(eos_pen)
    reward_arr = np.array(reward_vals)

    ax.bar(x, reward_arr, width, label="Net reward", color=CB_GREEN, edgecolor="white")
    ax.bar(x, boxed_arr, width, bottom=reward_arr,
           label=f"Box penalty (coef={FORMAT_COEF})", color=CB_ORANGE, alpha=0.8, edgecolor="white")
    ax.bar(x, eos_arr, width, bottom=reward_arr + boxed_arr,
           label=f"EOS penalty (coef={EOS_COEF})", color=CB_RED, alpha=0.7, edgecolor="white")

    for i in range(len(models)):
        ax.text(i, correct_arr[i] + 0.01, f"correct={correct_arr[i]:.1%}", ha="center", fontsize=8)
        ax.text(i, reward_arr[i] / 2, f"r={reward_arr[i]:.3f}", ha="center", fontsize=8,
                color="white", fontweight="bold")

    ax.set_xticks(x)
    ax.set_xticklabels(models, fontsize=9)
    ax.set_ylabel("Value")
    ax.set_title("Final Train Step: Reward = correct + penalties")
    ax.legend(fontsize=8)
    ax.grid(axis="y", alpha=0.3)
    save(fig, "06_reward_decomposition", fig6_reward_decomposition)


if __name__ == '__main__':
    all_data = load_all()
    fig6_reward_decomposition(all_data)
