#!/usr/bin/env python3
"""Reproduction script for 07_think_token_budget. Generated by gen_research_figures.py."""
import json, sys
from pathlib import Path
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# Style
plt.rcParams.update({
    "font.family": "serif", "font.size": 10, "axes.titlesize": 12,
    "axes.labelsize": 11, "legend.fontsize": 9, "xtick.labelsize": 9,
    "ytick.labelsize": 9, "savefig.dpi": 600, "savefig.bbox": "tight",
    "pdf.fonttype": 42, "ps.fonttype": 42,
    "axes.spines.top": False, "axes.spines.right": False,
})

CB_GREEN = "#009E73"; CB_RED = "#D55E00"; CB_BLUE = "#0072B2"
CB_ORANGE = "#E69F00"; CB_PURPLE = "#CC79A7"; CB_SKY = "#56B4E9"
MODEL_COLORS = {"GPT-OSS-20B": CB_BLUE, "Qwen3-30B-Instruct": CB_GREEN, "Qwen3-30B-Think": CB_RED}
MODEL_MARKERS = {"GPT-OSS-20B": "o", "Qwen3-30B-Instruct": "s", "Qwen3-30B-Think": "^"}

DATA_ROOT = Path("/tmp/tinker-examples/rlvr")
RUNS = {
    "GPT-OSS-20B": DATA_ROOT / "gptoss-20b-v3b" / "metrics.jsonl",
    "Qwen3-30B-Instruct": DATA_ROOT / "qwen3-30b-instruct-v3b" / "metrics.jsonl",
    "Qwen3-30B-Think": DATA_ROOT / "qwen3-30b-think-v3b" / "metrics.jsonl",
}

def load_all():
    result = {}
    for name, path in RUNS.items():
        data = [json.loads(l) for l in open(path)]
        train = [d for d in data if "env/all/correct" in d]
        evl = [d for d in data if "test/test/env/all/correct" in d]
        result[name] = (train, evl)
    return result

def save(fig, name):
    fig.savefig(f"{name}.png", dpi=600, bbox_inches="tight")
    fig.savefig(f"{name}.pdf", bbox_inches="tight")
    print(f"Saved {name}.png and {name}.pdf")

# --- Figure function ---
def fig7_think_token_trajectory(all_data):
    """Think model token budget across training — shows bimodality via train vs eval split."""
    fig, ax = plt.subplots(figsize=(8, 5))

    train_think, eval_think = all_data["Qwen3-30B-Think"]
    train_instruct, eval_instruct = all_data["Qwen3-30B-Instruct"]

    steps_t = [d["step"] for d in train_think]
    tokens_t = [d["env/all/ac_tokens_per_turn"] for d in train_think]
    ax.plot(steps_t, tokens_t, color=CB_RED, linewidth=1.5, alpha=0.7, label="Think (train)")

    eval_steps_t = [d["step"] for d in eval_think]
    eval_tokens_t = [d["test/test/env/all/ac_tokens_per_turn"] for d in eval_think]
    ax.plot(eval_steps_t, eval_tokens_t, color=CB_RED, marker="^", linewidth=2,
            markersize=8, linestyle="--", label="Think (eval)")

    steps_i = [d["step"] for d in train_instruct]
    tokens_i = [d["env/all/ac_tokens_per_turn"] for d in train_instruct]
    ax.plot(steps_i, tokens_i, color=CB_GREEN, linewidth=1.5, alpha=0.5, label="Instruct (train)")

    eval_steps_i = [d["step"] for d in eval_instruct]
    eval_tokens_i = [d["test/test/env/all/ac_tokens_per_turn"] for d in eval_instruct]
    ax.plot(eval_steps_i, eval_tokens_i, color=CB_GREEN, marker="s", linewidth=2,
            markersize=7, linestyle="--", alpha=0.7, label="Instruct (eval)")

    ax.set_xlabel("Training step")
    ax.set_ylabel("Mean tokens per turn")
    ax.set_title("Think vs Instruct: Token Budget Over Training")
    ax.legend()
    ax.grid(axis="y", alpha=0.3)
    save(fig, "07_think_token_budget", fig7_think_token_trajectory)


if __name__ == '__main__':
    all_data = load_all()
    fig7_think_token_trajectory(all_data)
