#!/usr/bin/env python3
"""Reproduction script for 08_truncation_rate. Generated by gen_research_figures.py."""
import json, sys
from pathlib import Path
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# Style
plt.rcParams.update({
    "font.family": "serif", "font.size": 10, "axes.titlesize": 12,
    "axes.labelsize": 11, "legend.fontsize": 9, "xtick.labelsize": 9,
    "ytick.labelsize": 9, "savefig.dpi": 600, "savefig.bbox": "tight",
    "pdf.fonttype": 42, "ps.fonttype": 42,
    "axes.spines.top": False, "axes.spines.right": False,
})

CB_GREEN = "#009E73"; CB_RED = "#D55E00"; CB_BLUE = "#0072B2"
CB_ORANGE = "#E69F00"; CB_PURPLE = "#CC79A7"; CB_SKY = "#56B4E9"
MODEL_COLORS = {"GPT-OSS-20B": CB_BLUE, "Qwen3-30B-Instruct": CB_GREEN, "Qwen3-30B-Think": CB_RED}
MODEL_MARKERS = {"GPT-OSS-20B": "o", "Qwen3-30B-Instruct": "s", "Qwen3-30B-Think": "^"}

DATA_ROOT = Path("/tmp/tinker-examples/rlvr")
RUNS = {
    "GPT-OSS-20B": DATA_ROOT / "gptoss-20b-v3b" / "metrics.jsonl",
    "Qwen3-30B-Instruct": DATA_ROOT / "qwen3-30b-instruct-v3b" / "metrics.jsonl",
    "Qwen3-30B-Think": DATA_ROOT / "qwen3-30b-think-v3b" / "metrics.jsonl",
}

def load_all():
    result = {}
    for name, path in RUNS.items():
        data = [json.loads(l) for l in open(path)]
        train = [d for d in data if "env/all/correct" in d]
        evl = [d for d in data if "test/test/env/all/correct" in d]
        result[name] = (train, evl)
    return result

def save(fig, name):
    fig.savefig(f"{name}.png", dpi=600, bbox_inches="tight")
    fig.savefig(f"{name}.pdf", bbox_inches="tight")
    print(f"Saved {name}.png and {name}.pdf")

# --- Figure function ---
def fig8_truncation_rate(all_data):
    fig, ax = plt.subplots(figsize=(8, 5))
    for name, (train, evl) in all_data.items():
        color = MODEL_COLORS[name]
        steps = [d["step"] for d in train]
        trunc = [1 - d["env/all/format_eos"] for d in train]
        ax.plot(steps, trunc, color=color, linewidth=1.2, alpha=0.6, label=f"{name} (train)")

        eval_steps = [d["step"] for d in evl]
        eval_trunc = [1 - d["test/test/env/all/format_eos"] for d in evl]
        ax.plot(eval_steps, eval_trunc, color=color, marker=MODEL_MARKERS[name],
                linewidth=2, markersize=7, linestyle="--", label=f"{name} (eval)")

    ax.set_xlabel("Training step")
    ax.set_ylabel("Truncation rate (1 \u2212 format_eos)")
    ax.set_title("Truncation Rate Over Training")
    ax.legend(fontsize=8)
    ax.set_ylim(bottom=0)
    ax.grid(axis="y", alpha=0.3)
    save(fig, "08_truncation_rate", fig8_truncation_rate)


if __name__ == '__main__':
    all_data = load_all()
    fig8_truncation_rate(all_data)
