#!/usr/bin/env python3
"""Reproduction script for 09_grader_accuracy. Generated by gen_research_figures.py."""
import json, sys
from pathlib import Path
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# Style
plt.rcParams.update({
    "font.family": "serif", "font.size": 10, "axes.titlesize": 12,
    "axes.labelsize": 11, "legend.fontsize": 9, "xtick.labelsize": 9,
    "ytick.labelsize": 9, "savefig.dpi": 600, "savefig.bbox": "tight",
    "pdf.fonttype": 42, "ps.fonttype": 42,
    "axes.spines.top": False, "axes.spines.right": False,
})

CB_GREEN = "#009E73"; CB_RED = "#D55E00"; CB_BLUE = "#0072B2"
CB_ORANGE = "#E69F00"; CB_PURPLE = "#CC79A7"; CB_SKY = "#56B4E9"
MODEL_COLORS = {"GPT-OSS-20B": CB_BLUE, "Qwen3-30B-Instruct": CB_GREEN, "Qwen3-30B-Think": CB_RED}
MODEL_MARKERS = {"GPT-OSS-20B": "o", "Qwen3-30B-Instruct": "s", "Qwen3-30B-Think": "^"}

DATA_ROOT = Path("/tmp/tinker-examples/rlvr")
RUNS = {
    "GPT-OSS-20B": DATA_ROOT / "gptoss-20b-v3b" / "metrics.jsonl",
    "Qwen3-30B-Instruct": DATA_ROOT / "qwen3-30b-instruct-v3b" / "metrics.jsonl",
    "Qwen3-30B-Think": DATA_ROOT / "qwen3-30b-think-v3b" / "metrics.jsonl",
}

def load_all():
    result = {}
    for name, path in RUNS.items():
        data = [json.loads(l) for l in open(path)]
        train = [d for d in data if "env/all/correct" in d]
        evl = [d for d in data if "test/test/env/all/correct" in d]
        result[name] = (train, evl)
    return result

def save(fig, name):
    fig.savefig(f"{name}.png", dpi=600, bbox_inches="tight")
    fig.savefig(f"{name}.pdf", bbox_inches="tight")
    print(f"Saved {name}.png and {name}.pdf")

# --- Figure function ---
def fig9_grader_accuracy(all_data):
    """Per-model grader false negative rates from experiment-log-session2.md.

    Actual measured FN rates on wrong-but-boxed answers:
    - GPT-OSS v3b: 14% (1/7)
    - Instruct v3b: 24% (5/21)
    - Think v3b: had a separate bug (\\boxed{answer} literal accepted)
    """
    fig, ax = plt.subplots(figsize=(7, 5))

    models = ["GPT-OSS-20B", "Qwen3-30B-Instruct", "Qwen3-30B-Think"]
    fn_counts = [1, 5]
    sample_sizes = [7, 21, None]
    fn_rates = [fn_counts[0] / sample_sizes[0], fn_counts[1] / sample_sizes[1], np.nan]
    colors = [MODEL_COLORS[m] for m in models]

    x = np.arange(len(models))
    bars = ax.bar(x[:2], fn_rates[:2], width=0.5, color=colors[:2], edgecolor="white")

    for i, bar in enumerate(bars):
        n = sample_sizes[i]
        c = fn_counts[i]
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.01,
                f"{c/n:.0%} ({c}/{n})", ha="center", fontsize=10, fontweight="bold")

    ax.bar(x[2], 0.02, width=0.5, color=colors[2], edgecolor="white", alpha=0.4)
    ax.text(x[2], 0.05, "grader bug:\n\\boxed{{answer}}\nliteral accepted",
            ha="center", fontsize=8, fontstyle="italic", color=CB_RED)

    ax.set_xticks(x)
    ax.set_xticklabels(models, fontsize=9)
    ax.set_ylabel("False negative rate (wrong answers graded correct)")
    ax.set_title("LLM Grader False Negative Rate by Model")
    ax.set_ylim(0, 0.35)
    ax.grid(axis="y", alpha=0.3)

    ax.text(0.98, 0.62,
            "Common FN causes:\n"
            "  LaTeX \\text{{}} wrapping\n"
            "  Variable name diffs\n"
            "  Double-boxing\n\n"
            "Small n (7, 21) \u2014\n"
            "rates are indicative",
            transform=ax.transAxes, ha="right", va="top", fontsize=8,
            color="gray", family="monospace",
            bbox=dict(boxstyle="round,pad=0.3", facecolor="whitesmoke", edgecolor="lightgray"))
    save(fig, "09_grader_accuracy", fig9_grader_accuracy)


if __name__ == '__main__':
    all_data = load_all()
    fig9_grader_accuracy(all_data)
